var personname = "Owais";
console.log("your name -- `Owais`? I predict true.");
console.log(personname == "Owais");
var college = "National college";
console.log("you are study in -- `National college`? I predict true.");
console.log(college == "National college");
var number = 2 + 3;
console.log("is 2 + 3 == `5`? it is correct.");
console.log(number == 5);
var weather = "Cloudy";
console.log("Today weather is == `Cloudy`? I predict true.");
console.log(weather == "Cloudy");
var car = "red";
console.log("her car colour is == `red`? Is this true.");
console.log(car == "red");
var laptop = "lenovo";
console.log("you've hp == `laptop`? am i right. ");
console.log(laptop == "hp");
var shoes = "nike";
console.log("you've bata == `shoes`? am i right.");
console.log(shoes == "bata");
var mobile = "iphone";
console.log("you've `android` phone? am i right.");
console.log(mobile == "android");
var computer = "i5";
console.log("your computer model is == `i7`? i predict right.");
console.log(computer == "i7");
var instagram = "application";
console.log("instagram is a == `browser`? is this right.");
console.log(instagram == "browser");
